# Copyright 2023-2025 Overte e.V.
# SPDX-License-Identifier: Apache-2.0

name: Production CI Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build_website:
    runs-on: ubuntu-24.04

    name: Build and deploy website
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Build website
      shell: bash
      run: |
        make BUILDDIR="build/en" html
        mv build/en/html/ output/

    - name: Build German translation
      run: |
        make BUILDDIR="build/de" SPHINXOPTS="-Dlanguage=de" html
        mv build/de/html/ output/de/

    - name: Build Japanese translation
      run: |
       make BUILDDIR="build/ja" SPHINXOPTS="-Dlanguage=ja" html
       mv build/ja/html/ output/ja/

    - name: Build traditional Chinese translation
      run: |
       make BUILDDIR="build/zh_Hant" SPHINXOPTS="-Dlanguage=zh_Hant" html
       mv build/zh_Hant/html/ output/zh_Hant/

    - name: Build Czech translation
      run: |
       make BUILDDIR="build/cs" SPHINXOPTS="-Dlanguage=cs" html
       mv build/cs/html/ output/cs/

    - name: Build Korean translation
      run: |
       make BUILDDIR="build/ko" SPHINXOPTS="-Dlanguage=ko" html
       mv build/ko/html/ output/ko/

    - name: Build Lithuanian translation
      run: |
       make BUILDDIR="build/lt" SPHINXOPTS="-Dlanguage=lt" html
       mv build/lt/html/ output/lt/

    - name: Build French translation
      run: |
       make BUILDDIR="build/fr" SPHINXOPTS="-Dlanguage=fr" html
       mv build/fr/html/ output/fr/

    - name: Build Portuguese translation
      run: |
       make BUILDDIR="build/pt" SPHINXOPTS="-Dlanguage=pt" html
       mv build/pt/html/ output/pt/

    - name: Build Russian translation
      run: |
       make BUILDDIR="build/ru" SPHINXOPTS="-Dlanguage=ru" html
       mv build/ru/html/ output/ru/
    
    - name: Build Spanish translation
      run: |
       make BUILDDIR="build/es" SPHINXOPTS="-Dlanguage=es" html
       mv build/es/html/ output/es/

    - name: Deploy website
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: www531.your-server.de
        protocol: ftps
        username: ${{ secrets.GHA_HETZNER_WEBSITE_FTP_USER }}
        password: ${{ secrets.GHA_HETZNER_WEBSITE_FTP_PASS }}
        local-dir: ./output/
        server-dir: /
        exclude: |
          .htaccess
