name: Master CI Check Warnings

on:
  push:
    branches:
      - master

jobs:
  check_warnings:
    runs-on: ubuntu-22.04

    name: Check for warnings
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check source
      shell: bash
      run: |
        make SPHINXOPTS="-W --keep-going" html
    - name: Check German
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-de SPHINXOPTS="-Dlanguage=de -W --keep-going" html
    - name: Check French
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-fr SPHINXOPTS="-Dlanguage=fr -W --keep-going" html
    - name: Check Japanese
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-jp SPHINXOPTS="-Dlanguage=jp -W --keep-going" html
    - name: Check Spanish
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-es SPHINXOPTS="-Dlanguage=es -W --keep-going" html
    - name: Check Korean
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-ko SPHINXOPTS="-Dlanguage=ko -W --keep-going" html

    - name: Check traditional Chinese
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-zh_Hant SPHINXOPTS="-Dlanguage=zh_Hant -W --keep-going" html

    - name: Check Czech
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-cs SPHINXOPTS="-Dlanguage=cs -W --keep-going" html

    - name: Check Lithuanian
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-lt SPHINXOPTS="-Dlanguage=lt -W --keep-going" html

    - name: Check Portuguese
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-pt SPHINXOPTS="-Dlanguage=pt -W --keep-going" html

    - name: Check Russian
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-ru SPHINXOPTS="-Dlanguage=ru -W --keep-going" html
