name: Pull Request CI Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_en_docs:
    runs-on: ubuntu-24.04

    name: Build to check for warnings
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build documentation
      shell: bash
      run: |
        # Return 1 on warning but do not exit
        make SPHINXOPTS="-W --keep-going" html
        mkdir -p build-archives
