name: Translation files CI update

on:
  push:
    branches:
      - master
    # Only run if something other than locales are updated.
    # This is to prevent this workflow from running when Weblate commits new translations.
    paths-ignore:
      - 'source/locales/**'

jobs:
  regenerate_locales_docs:
    runs-on: ubuntu-24.04

    name: Update translation files
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Regenerate translation files
      shell: bash
      run: |
        make gettext
        sphinx-intl update
    - name: Commit changes
      uses: actions-x/commit@v6
      with:
        name: AnimatedMannequin
        email: AnimatedMannequin@overte.org
        message: Automatically updated locales
        files: source/locales/**
        token: ${{ secrets.ANIMATED_MANNEQUIN_COMMIT_TOKEN }}
